name: gimp
version: 3.0.0-RC2
summary: GNU Image Manipulation Program
description: |
  Whether you are a graphic designer, photographer, illustrator, or scientist,
  GIMP provides you with sophisticated tools to get your job done. You can
  further enhance your productivity with GIMP thanks to many customization
  options and 3rd party plugins.

grade: stable
confinement: strict
base: core24
compression: lzo

platforms:
  arm64:
  amd64:

layout:
  /etc/gimp:
    bind: $SNAP/etc/gimp
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/babl-0.1:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/babl-0.1
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gegl-0.4:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gegl-0.4
  /usr/share/locale:
    bind: $SNAP/usr/share/locale

slots:
  dbus-gimp:
    interface: dbus
    bus: session
    name: org.gimp.GIMP.UI

plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs
  openvino-libs:
    interface: content
    content: openvino-libs-2404
    target: $SNAP/openvino
  openvino-ai-plugins-gimp-libs:
    interface: content
    content: openvino-ai-plugins-gimp-2404
    target: $SNAP/openvino-ai-plugins-gimp
  dot-local-share-openvino-ai-plugins-gimp:
    interface: personal-files
    write:
      - $HOME/.local/share/openvino-ai-plugins-gimp

environment:
  GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gjs/girepository-1.0:$GI_TYPELIB_PATH
  LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/gnome-platform/usr/lib:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/npu-libs
  # Ensure the gmic plugin can correctly locate the QT plugins
  QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
  GIMP3_LOCALEDIR: $SNAP/usr/share/locale
  # Lua goat exercise considered unstable upstream: https://gitlab.gnome.org/GNOME/gimp/-/commit/78665ca3723f723ac313fdaeef5b62d41ab6b48d
  # The extension will fail on GIMP startup but commenting these lines avoids the risk of a nasty crash loop
  #LUA_PATH: $SNAP/usr/share/lua/5.1/?.lua;$SNAP/usr/share/lua/5.1/lgi/?.lua;$SNAP/usr/share/lua/5.1/lgi/override/?.lua
  #LUA_CPATH: $SNAP/usr/lib/x86_64-linux-gnu/lua/5.1/?.so

apps:
  gimp:
    command: usr/bin/gimp
    command-chain: ["command-chain/openvino-launch", "command-chain/openvino-ai-plugins-gimp-launch"]
    extensions: [gnome]
    desktop: usr/share/applications/gimp.desktop
    common-id: org.gimp.GIMP
    environment:
      HOME: $SNAP_REAL_HOME
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
    slots:
      - dbus-gimp
    plugs:
      - cups-control
      - browser-support
      - home
      - network
      - removable-media
      - unity7
      - intel-npu
      - npu-libs
      - openvino-libs
      - openvino-ai-plugins-gimp-libs
      - dot-local-share-openvino-ai-plugins-gimp

parts:
  babl:
    plugin: meson
    source: https://github.com/GNOME/babl.git
    source-tag: BABL_0_1_110
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dwith-docs=false
    build-packages:
      - w3m

  gegl:
    after:
      - babl
    source: https://github.com/GNOME/gegl.git
    source-tag: GEGL_0_4_52
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Ddocs=false
      - -Dworkshop=true
    build-environment:
      - C_INCLUDE_PATH: /snap/gnome-46-2404-sdk/current/usr/include/librsvg-2.0:${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}
      - PKG_CONFIG_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - PATH: /snap/ffmpeg-2404-sdk/current/usr/bin${PATH:+:$PATH}
    build-packages:
      - libexiv2-dev
      - libfftw3-dev
      - libgexiv2-2
      - libglib2.0-dev
      - libglu1-mesa-dev
      - liblensfun-dev
      - libluajit-5.1-dev
      - libmaxflow-dev
      - libopenexr-dev
      - libraw-dev
      - libsdl2-dev
      - libspiro-dev
      - libsuitesparse-dev
      - libv4l-dev
      - libwebp-dev
    stage-packages:
      - libamd3
      - libbtf2
      - libcamd3
      - libccolamd3
      - libcholmod5
      - libcolamd3
      - libcxsparse4
      - libexiv2-27
      - libgexiv2-2
      - libgraphblas7
      - libklu2
      - liblapack3
      - libldl3
      - liblensfun1
      - libluajit-5.1-2
      - libmaxflow0
      - libopenexr-3-1-30
      - libraw-bin
      - librbio4
      - libsdl2-2.0-0
      - libspiro1
      - libspqr4
      - libumfpack6
      - libv4l-0
    build-snaps:
      - ffmpeg-2404

  gimp:
    after:
      - babl
      - gegl
    plugin: meson
    source: https://github.com/GNOME/gimp.git
    override-pull: |
      tag="$(echo "GIMP_${SNAPCRAFT_PROJECT_VERSION}" | tr "." "_"  | tr "-" "_")"
      git clone -b "$tag" https://github.com/GNOME/gimp.git "$CRAFT_PART_SRC"
      sed -i "s|gitlab.gnome.org|github.com|" "$CRAFT_PART_SRC"/.gitmodules
      git submodule update --init
      sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/256x256/apps/gimp.png|' desktop/gimp.desktop.in.in
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dgi-docgen=disabled
      - -Dg-ir-doc=false
      - -Dbuild-id=org.gimp.GIMP.snapcraft.preview
      - -Dbug-report-url=https://github.com/snapcrafters/gimp/issues/
      - -Dcheck-update=no
      - -Denable-default-bin=enabled
      - -Drelocatable-bundle=yes
      - -Dlibunwind=true
    build-environment:
      - BABL_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/babl-0.1
      - GEGL_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gegl-0.4
      - GI_TYPELIB_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:$GI_TYPELIB_PATH
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - C_INCLUDE_PATH: /snap/gnome-46-2404-sdk/current/usr/include/librsvg-2.0:${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}
    build-packages:
      - automake
      - intltool
      - iso-codes
      - libaa1-dev
      - libappstream-glib-dev
      - libart-2.0-dev
      - libbz2-dev
      - libcairo-gobject2
      - libexif-dev
      - libexpat1-dev
      - libfftw3-dev
      - libgexiv2-dev
      - libgpm-dev
      - libice-dev
      - libluajit-5.1-dev
      - liblzma-dev
      - libmng-dev
      - libmypaint-dev
      - libopenexr-dev
      - libslang2-dev
      - libsm-dev
      - libunwind-dev
      - libwebp-dev
      - libwmf-dev
      - libxmu-dev
      - libxpm-dev
      - luajit
      - poppler-data
      - xdg-utils
      - xsltproc
    stage-packages:
      - evince
      - ghostscript
      - iso-codes
      - libaa1
      - libappstream-glib8
      - libart-2.0-2
      - libbz2-1.0
      - libexif12
      - libfftw3-bin
      - libgexiv2-2
      - libgpm2
      - libheif1
      - libluajit-5.1-2
      - liblzma5
      - libmng2
      - libmypaint-1.5-1
      - libmypaint-common
      - libopenexr-3-1-30
      - libslang2
      - libsndio7.0
      - libunwind8
      - libwebp7
      - libwebpdemux2
      - libwebpmux3
      - libwmf-0.2-7
      - libxmu6
      - libxpm4
      - libxv1
      - lua-lgi
      - luajit
      - mypaint-brushes
      - mypaint-data
      - poppler-data
    override-stage: |
      # fix gimp python interpreters file
      cat <<EOF > ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gimp/3.0/interpreters/pygimp.interp
      python=/usr/bin/python3
      python3=/usr/bin/python3
      /usr/bin/python=/usr/bin/python3
      /usr/bin/python3=/usr/bin/python3
      :Python:E::py::python3:
      EOF
      # update gimp's plugin search path so it will pick up plugins mounted over snapd's content interface
      current_path=$(grep "# (plug-in-path" ${CRAFT_PART_INSTALL}/etc/gimp/3.0/gimprc | cut -d '"' -f2)
      add_dir=/snap/${SNAPCRAFT_PROJECT_NAME}/current/openvino-ai-plugins-gimp/gimp-plugins
      echo "(plug-in-path \"${current_path}:${add_dir}\")" >> ${CRAFT_PART_INSTALL}/etc/gimp/3.0/gimprc
      craftctl default

  command-chain-openvino:
    plugin: dump
    source-type: git
    source: https://github.com/canonical/openvino-toolkit-snap.git
    source-tag: 2024.6.0-1
    stage:
      - command-chain/openvino-launch

  command-chain-openvino-ai-plugins-gimp:
    plugin: dump
    source-type: git
    source: https://github.com/canonical/openvino-ai-plugins-gimp-snap.git
    source-tag: v2.99-R3.1-1
    stage:
      - command-chain/openvino-ai-plugins-gimp-launch

  gmic:
    after: [gimp]
    plugin: dump
    source: https://gmic.eu/files/source/gmic_3.5.0.tar.gz
    build-environment:
      - QT_SELECT: qt6
    build-packages:
      - cmake
      - pkg-config
      - qt6-base-dev
      - qt6-l10n-tools
      - qt6-tools-dev
      - qt6-wayland-dev
      - qtchooser
      - wget
    stage-packages:
      - libcurl4
      - libdouble-conversion3
      - libfftw3-bin
      - libffi8
      - libgraphicsmagick-q16-3
      - libgraphicsmagick++-q16-12
      - libjpeg-turbo8
      - libopencv-core406t64
      - libopencv-highgui406t64
      - libopencv-video406t64
      - libopenexr-3-1-30
      - libpng16-16
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6network6t64
      - libqt6widgets6t64
      - qt6-wayland
    override-build: |
      qtchooser -install qt6 "$(which qmake6)" || true
      make -C src CImg.h gmic_stdlib_community.h

      cd gmic-qt
      # The CMakeLists.txt file hard-codes a minimum QT6 version of 6.5.0, which is not available
      # in Noble. Testing confirms that things seem to work fine on the version in Noble (6.4.2).
      sed -i "s|set(MIN_QT_VERSION 6.5.0)|set(MIN_QT_VERSION 6.4.0)|g" CMakeLists.txt

      mkdir build
      cd build
      cmake \
        -DGMIC_QT_HOST=gimp3 \
        -DGMIC_PATH=$CRAFT_PART_SRC/src \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_SYSTEM_GMIC=OFF \
        -DBUILD_WITH_QT6=ON \
        ..

      make

      install -Dm 0755 $CRAFT_PART_BUILD/gmic-qt/build/gmic_gimp_qt \
        $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gimp/3.0/plug-ins/gmic_gimp_qt/gmic_gimp_qt

  cleanup:
    after: [gmic]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      for snap in "core24" "gnome-46-2404" "ffmpeg-2404"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done
