name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch.
  push:
    branches: ["2.99-openvino"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  get-architectures:
    name: 🖥 Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: 🖥 Get snap architectures
        id: get-architectures
        uses: snapcrafters/ci/get-architectures@main

  release:
    name: 🚢 Release to 2.99-openvino/candidate
    needs: get-architectures
    runs-on: self-hosted
    timeout-minutes: 1440
    environment: "2.99 OpenVino Candidate Branch"
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: 🚢 Release to 2.99-openvino/candidate
        uses: snapcrafters/ci/release-to-candidate@main
        with:
          architecture: ${{ matrix.architecture }}
          channel: 2.99-openvino/candidate
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          repo-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}

  call-for-testing:
    name: 📣 Create call for testing
    needs: [release, get-architectures]
    environment: "2.99 OpenVino Candidate Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: 📣 Create call for testing
        id: issue
        uses: snapcrafters/ci/call-for-testing@main
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          channel: 2.99-openvino/candidate
          github-token: ${{ secrets.GITHUB_TOKEN }}
          promotion-channel: 2.99-openvino/stable

  screenshots:
    name: 📸 Gather screenshots
    needs: call-for-testing
    environment: "2.99 OpenVino Candidate Branch"
    runs-on: self-hosted
    steps:
      - name: 📸 Gather screenshots
        uses: snapcrafters/ci/get-screenshots@main
        with:
          channel: 2.99-openvino/candidate
          issue-number: ${{ needs.call-for-testing.outputs.issue-number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          screenshots-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
